-- =========================================================
-- SIMBERPAS ENTERPRISE V4 — MIGRATION
-- Jalankan satu kali di Supabase > SQL Editor.
-- Kompatibel dengan tabel upt dan berita versi sebelumnya.
-- =========================================================

create extension if not exists pgcrypto;

-- 1. Perkaya tabel UPT untuk peta dan scoping akses.
alter table public.upt add column if not exists jenis_upt text;
alter table public.upt add column if not exists provinsi text;
alter table public.upt add column if not exists kanwil text;
alter table public.upt add column if not exists latitude double precision;
alter table public.upt add column if not exists longitude double precision;
alter table public.upt add column if not exists coordinate_quality text;
alter table public.upt add column if not exists updated_at timestamptz not null default now();

-- 2. Perkaya berita untuk workflow verifikasi dan AI.
alter table public.berita add column if not exists updated_at timestamptz not null default now();
alter table public.berita add column if not exists status_verifikasi text not null default 'Draft';
alter table public.berita add column if not exists verified_by text;
alter table public.berita add column if not exists verified_at timestamptz;
alter table public.berita add column if not exists kata_kunci text[];
alter table public.berita add column if not exists lokasi text;
alter table public.berita add column if not exists tingkat_perhatian text default 'Rendah';
alter table public.berita add column if not exists ai_provider text default 'rules';
alter table public.berita add column if not exists ai_confidence numeric(4,3);

-- 3. Pengguna aplikasi dan role bertingkat.
create table if not exists public.app_users (
    id uuid primary key default gen_random_uuid(),
    username text not null unique,
    password_hash text not null,
    full_name text not null,
    role text not null check (role in ('super_admin','admin_pusat','admin_kanwil','operator_upt','viewer')),
    assigned_kanwil text,
    assigned_upt text,
    aktif boolean not null default true,
    last_login timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists app_users_username_lower_idx
    on public.app_users (lower(username));

-- 4. Audit log aktivitas.
create table if not exists public.audit_log (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    actor_username text not null,
    actor_role text not null,
    action text not null,
    entity text not null,
    entity_id text,
    metadata jsonb not null default '{}'::jsonb
);

create index if not exists audit_log_created_at_idx on public.audit_log (created_at desc);
create index if not exists audit_log_actor_idx on public.audit_log (actor_username);
create index if not exists upt_provinsi_idx on public.upt (provinsi);
create index if not exists upt_kanwil_idx on public.upt (kanwil);
create index if not exists berita_status_verifikasi_idx on public.berita (status_verifikasi);
create index if not exists berita_urgensi_idx on public.berita (urgensi);

-- 5. Trigger updated_at.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_upt_updated_at on public.upt;
create trigger trg_upt_updated_at before update on public.upt
for each row execute function public.set_updated_at();

drop trigger if exists trg_berita_updated_at on public.berita;
create trigger trg_berita_updated_at before update on public.berita
for each row execute function public.set_updated_at();

drop trigger if exists trg_app_users_updated_at on public.app_users;
create trigger trg_app_users_updated_at before update on public.app_users
for each row execute function public.set_updated_at();

-- 6. RLS aktif. Aplikasi server-side memakai secret/service-role key.
alter table public.upt enable row level security;
alter table public.berita enable row level security;
alter table public.app_users enable row level security;
alter table public.audit_log enable row level security;

grant all on public.upt to service_role;
grant all on public.berita to service_role;
grant all on public.app_users to service_role;
grant all on public.audit_log to service_role;
grant usage, select on all sequences in schema public to service_role;
